import './globals.css'

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <head>
        <title>Portfolio Alexander Truyaert</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </head>
      <body>
        <header>
          <h1><a href="/">Alexander Truyaert</a></h1>
          <nav>
            <a href="/about">About me</a>
            <a href="/blog">Blog</a>
            <a href="/projects">Projects</a>
          </nav>
        </header>
        {children}
        </body>
    </html>
  )
}
